### ISSUE TITLE
error when importing a BON file

### ISSUE THREAD

**Issue by RaphaelDrewBoltman** [Psycrow101/Blender-3D-STH-Mtn-plugin#1]
Hello! i have an issue while importing the .BON from Super Shadow winning event scene:
![blender_zJmOdQhfB8](https://user-images.githubusercontent.com/50070802/152647816-a8267ff8-db87-4d0a-9a9a-c14ba84be229.png)
If you ignore the error and import the MTN, this error popup will then show up
![blender_6vRkL84fwn](https://user-images.githubusercontent.com/50070802/152647995-0f238db3-f133-4711-bf84-6f98201f64c4.png)

In case you need the files, i am also providing those here:
[SUPERSHADOW!LOCATOR.zip](https://github.com/Psycrow101/Blender-3D-STH-Mtn-plugin/files/8008261/SUPERSHADOW.LOCATOR.zip)

Thanks for making this plugin and the ANM Import/Export from both Sonic Heroes and Shadow The Hedgehog for Blender, by the way! Lets hope people start modding the game without expensive gear and start using free alteratives!

**Comment by Psycrow101** [comment]
Thanks for the feedback, I really appreciate it.

Looks like the bone was not found by the tag obtained from BON (in this case the value of the tag was -1). I've updated the plugin to address this issue, but I need more research to make sure I'm not missing something important.

![image](https://user-images.githubusercontent.com/31922454/152652821-631c8c5d-eed7-41b5-a730-9bfe318a7b86.png)

**Comment by RaphaelDrewBoltman** [comment]
Thanks for your reply!
Importing the bones and the animation now work!
I'm coming with another issue regarding Sonic Heroes' ANM exporting. despite being in the wrong issue now, and the "[unstable]" label on the name, it might be important to show: 
![image](https://user-images.githubusercontent.com/50070802/152664037-f94223cf-3a64-4f6e-a01c-a9c67b05f343.png)

I also wanted to ask you if you want to join our [Sonic Heroes and Shadow The Hedgehog Modding Community on Discord](https://discord.gg/dKpUwJZ9), where we are working on various departments (specially scripts and plugins, we are discovering DeltaMorph modding right now) and I believe it would be amazing if you want to join us so you can show up and discuss your work for the games, it's also where we have most resources of modding both games so feel free to join >> [link](https://discord.gg/dKpUwJZ9)

**Comment by Psycrow101** [comment]
Thanks for the invitation!

Can you attach any files (or .blend) that you are having problems with? I will try to fix this and improve the export if possible.

**Comment by dreamsyntax** [comment]
I'll sync with Raph on this and recreate it, and attach blend if its still an issue.

**Comment by dreamsyntax** [comment]
@RaphaelDrewBoltman looks like there's no issue with the latest multi-mesh version of DragonFF (and probably the current master) + io_scene_sth_mtn 0.1.0.

https://github.com/Psycrow101/Blender-3D-STH-Mtn-plugin/assets/14857235/9da28d74-1026-4712-a324-a580921e29d8
